### ISSUE TITLE
ストーンの杖の挙動がおかしい？（杖にするとおかしくなる　今年の３月から）

### ISSUE THREAD

**Issue by ngmansion** [ngmansion/FE8N#19]
報告より転記
ストーンの杖なんて作った事ないので、何が正しいのか分からないが。。。

**Comment by Isaac45132** [comment]
ストーンバグの原因は２つありました
まず風薙ぎの処理のなかでストーンなら必ず反撃不可にするという記述があるのですが
これが何故かうまく働いてなかったです
これだけを直しても正常に動かせるのですが、敵をストーン状態にしても反撃してきます
それで叫喚の反撃不可効果辺りを探してみたら
石化の反撃不可効果へジャンプする記述がなぜなnop（何もしない）になってました

**Comment by ngmansion** [comment]
ストーンの杖というのが元々存在しないものなので、正解値が分からないのが一番の困り事です。

・元々どんな挙動なのか
・今がどんな挙動なのか
が分かれば対応できるかと思います

**Comment by Isaac45132** [comment]
一応こちらですでに修正したので、こちらも対応が必要ないかもしれません。https://gyazo.com/0009bdb9bafde52700c887f1b9840b11
ストーンの杖の設定。
元々は原作にある魔法ストーンのような動作をします。ですが以前、叫喚を奥義にしてもらった時に、ストーンの命中率が強制的に0％＆動作が発動せずにそのままフリーズするという現象がありました。
直したのは下記ですまず風薙ぎの処理のなかでストーンなら必ず反撃不可にするという記述があるのですが
これが何故かうまく働いてなかったです
これだけを直しても正常に動かせるのですが、敵をストーン状態にしても反撃してきます
それで叫喚の反撃不可効果辺りを探してみたら
石化の反撃不可効果へジャンプする記述がなぜなnop（何もしない）になってました

     ----- Original Message -----

**Comment by ngmansion** [comment]
ありがとうございます。考えてみます。
今のところの想定としては…
・前半の指摘は、チェックしたかどうか忘れました。ここがうまく動いていないなら直したいです
・後半の指摘は、バグではなく意図的な変更で変えたくない所なので、ここはそのままにしたいと思ってます

**Comment by ngmansion** [comment]
前半側だけでなんとかするのが無理っぽかったので、
後半部分を元の意図を崩さないように工夫して修正
