### ISSUE TITLE
フキダシの表示ステータス改善

### ISSUE THREAD

**Issue by aera-ngmansion** [ngmansion/FE8N#29]
[目的]
フキダシへの攻速守魔の表示

**Comment by ngmansion** [comment]
点滅とはいえ、表示は実現できたので一旦終わり

**Comment by aera-ngmansion** [comment]
![](https://i.imgur.com/Gijx88N.png)

**Comment by aera-ngmansion** [comment]
![](https://i.imgur.com/SnLKYbs.png)
他の改造の見た目を拝借
これを目指して、もう少し粘りたい
