### ISSUE TITLE
スキル課題管理(総合)

### ISSUE THREAD

**Issue by ngmansion** [ngmansion/FE8N#30]
スキル/戦技/奥義 関連の打ち上げの場。

基本的に何かあれば新しいissue立ち上げで良いが、
スキル関連は細かい打ち上げ事項が多そうなので作成。

**Comment by ngmansion** [comment]
城塞の効果変更
新: 攻撃-1防御耐魔+3
旧: 攻撃-2防御耐魔+4

ノーデメリットの凪と比較して微妙過ぎるので、効果+4にする事で差別化する狙い
(この課題には元々気づいていて、昔は効果が+6だったが、強すぎると指摘を受けたので+3に下げていた)

**Comment by ngmansion** [comment]
クローズ状態の方が邪魔にならなさそうなので試しにクローズ

**Comment by aera-ngmansion** [comment]
瞬撃効果を完全にイメージ優先で飛燕につけていたが、
やっぱりFEH通りに金剛 or 明鏡の一撃につけるべきかな・・・

**Comment by aera-ngmansion** [comment]
ロングレンジ戦技はGBAの仕様上再現困難なので、FEHにおけるロングレンジの表現である反撃不可で代用してみた狙撃

**Comment by aera-ngmansion** [comment]
獅子王の構えの性能は原作再現だが、弱そう

**Comment by aera-ngmansion** [comment]
https://github.com/ngmansion/FE8N/discussions/54 へ移行
