### ISSUE TITLE
引き戻し(Reposition)

### ISSUE THREAD

**Issue by aera-ngmansion** [ngmansion/FE8N#38]
相当以前(FEHより前)からやりたかったが諦めてた事。何番煎じレベルではある。
![](https://i.imgur.com/Ai61jIH.gif)
![](https://i.imgur.com/w9FHQ6w.gif)

現在：
試験運用中

**Comment by aera-ngmansion** [comment]
できそう。後、バグがあったので直す予定

**Comment by aera-ngmansion** [comment]
完成。しばらく動かして不具合が無ければcloseする

**Comment by Isaac45132** [comment]
こんばんは

_N→EquipmentPopupと_N→status2の
ファイルを一度消し、正常版のそれらのファイルを入れて、N→_Skills→_commonのiconEXの]sファイルとdmpファイルを上書きして、写真のバージョンに戻したのですがスキル説明欄がずれています。
他に戻す箇所はありますか？
