### ISSUE TITLE
ユニットが移動力の最大で移動した時にフリーズ（極まれ）

### ISSUE THREAD

**Issue by Isaac45132** [ngmansion/FE8N#45]
ユニットが移動力の最大で移動した時にフリーズ（極まれ）します。
移動７のユニットが７マス移動を指定して移動した瞬間に画面が乱れ異音を吐きます。
症状としては、ユニット命令でマップ外に移動するように指定した時みたいなかんじ？

発生日は今年の９月から。
リセットすると発動しないのでセーブデータは用意できていません。
良かったらありえそうな箇所をもう一度みてもらえないでしょうか？

**Comment by aera-ngmansion** [comment]
たぶん直しました

**Comment by Isaac45132** [comment]
バグがまた起こったのを確認しました。
症状としてはやはり、最大移動でフリーズ。ユニット操作の矢印がムチャクチャになる等です。

**Comment by aera-ngmansion** [comment]
@Isaac45132 
通知があった事に気づいたのですが、直りませんでした？
とはいえ、他に原因は思いつかないのですが。

**Comment by Isaac45132** [comment]
すいません、こことは別の所に要因を見つけたので解決しました。
お手数おかけしました。

**Comment by aera-ngmansion** [comment]
解決したようなのでclose
