### ISSUE TITLE
スキル説明欄がずれています。

### ISSUE THREAD

**Issue by aera-ngmansion** [ngmansion/FE8N#47]
こんばんは

_N→EquipmentPopupと_N→status2の
ファイルを一度消し、正常版のそれらのファイルを入れて、N→_Skills→_commonのiconEXの]sファイルとdmpファイルを上書きして、写真のバージョンに戻したのですがスキル説明欄がずれています。
他に戻す箇所はありますか？

_Originally posted by @Isaac45132 in https://github.com/ngmansion/FE8N/issues/38#issuecomment-735818781_

**Comment by aera-ngmansion** [comment]
ファイルを戻すだけでは解決しないものはいくつかあるので、今回のケースはそれに該当すると思います。
なので回答としては「ファイルを戻すだけでは戻りません」になると思います。

**Comment by aera-ngmansion** [comment]
対応完了

**Comment by Isaac45132** [comment]
Aeraさん　おはようございます。
pngをdmpファイルに変換するのってどうやられてますか？

**Comment by aera-ngmansion** [comment]
EventAssemblerに入っているPng2Dmp.exeで出来ますよ
ちなみにdmpと言っても無圧縮画像と圧縮画像があるのはご存じですか？
無圧縮画像のファイルを作るだけなら、Png2Dmp.exeにpngをドラッグアンドドロップすれば作れます
圧縮画像作るなら、--lz77のオプションが必要です
