### ISSUE TITLE
疲労カウンタの最大値を増やす

### ISSUE THREAD

**Issue by aera-ngmansion** [ngmansion/FE8N#52]
現在:  3 (=2bit)
予定: 31(=5bit)

余ってた2bitを有効活用出来ないか？と思って作ったのが「疲労」なので、最大3にゲーム性的な意味はない。
セーブ改変の都合でさらに3bit余った為、活用法を考えたが「疲労」くらいしか思いつかなかった。

但し、疲労最大値を増やしたところでどのように活用するかは考えてない
最大HPと同値にできれば、もっと原作に寄せた仕様に出来ると思うのだが、
今の想定の最大値だと「帯に短しタスキに長し」になるとも思っている。

**Comment by Isaac45132** [comment]
製作者が章毎の戦闘回数を設定出来てそれを超えると疲労というのはどうでしょう？
その戦闘回数を表示させるのが難しそうですがｗ

**Comment by aera-ngmansion** [comment]
その案を実現するにしても、戦闘回数カウンタが最大31じゃ足りなさそうに思えますね

中断セーブだけであればもっと行けると思うんですが・・・だからと言って何？な感じです

**Comment by aera-ngmansion** [comment]
https://github.com/ngmansion/FE8N/discussions/55
