### ISSUE TITLE
魔力パッチのレベルアップ処理で幸運が上がらない

### ISSUE THREAD

**Issue by Isaac45132** [ngmansion/FE8N#84]
LVUPで幸運が上がる時クラス上限をチェックしてますが
クラスの名前IDを上限として読み込んでいるようです。

**Comment by sigerudo** [comment]
安易な方法ですが、バグの改善方法としては
r3=00なら分岐してr1=0x1Eで大丈夫だと思います

**Comment by aera-ngmansion** [comment]
解析ありがとうございます　助かります

**Comment by aera-ngmansion** [comment]
解析コメント拝見しながら、そういえばそんなパッチ作ったなぁ、と思い出しました
幸運上限に関して何かケアしようと思いつつも忘れてたって感じがしますね…
