### ISSUE TITLE
スキル書関連バグ

### ISSUE THREAD

**Issue by aera-ngmansion** [ngmansion/FE8N#94]
#93 から派生
#46 の時のミスと思われる
２，３ほどのバグの複合になっている感があるので、現象をまとめつつ修正する

・4スキル目のスキルデータに設定処理の誤り→ fix
・スキル書を上限を超えて使える→ fix
・スキルを多く習得している時にEraserを使った時の挙動が不正→ fix

**Comment by aera-ngmansion** [comment]
とりあえず見つかったものは直ったハズ

**Comment by Isaac45132** [comment]
いまの8Nとうちってスキルの仕様違ったと思うんですが大丈夫ですかね？

そのまま当ててみたら、スキルの書は使えるけど表示はされない＆解除M仕様すると
以下画像でフリーズみたいになっちゃったのです。。
https://gyazo.com/b373ba88e461f07213f5a1297fed78fb

**Comment by aera-ngmansion** [comment]
見た目ほど大した変更はしてないのと、
スキル書関連は変わってない（少なくとも自分は変えてない・・・ハズ）+ conflict無しだったので、
問題ない想定だったんですが、当てが外れましたかね
